# Generated by Django 6.0.3 on 2026-06-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joueurtennis",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="joueurtennis",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
